{{- if or .Values.db.hostAddress .Values.db.disablePVC }}
{{ else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: determined-db-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: determined-db-{{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "determined.storageSize" }}
  {{- if .Values.db.storageClassName }}
  storageClassName: block-nvme-{{ include "determined.region" . | lower }}
  {{ end }}
{{ end }}
