apiVersion: v1
name: determined
description: An open source deep learning training platform with support for distributed training and hyperparameter search.
version: "0.18.72"
icon: https://github.com/determined-ai/determined/blob/master/determined-logo.png?raw=true
home: https://www.determined.ai/
annotations:
  category: MachineLearning

# appVersion controls the version Determined that is deployed. If using a
# a non-release version (e.g., X.Y.Z.dev0) you will have to specify an
# existing official release version (e.g., X.Y.Z) or specify a commit has
# that has been publicly published (all commits from master).
appVersion: "0.21.0"
